# Generated by Django 4.1.2 on 2022-10-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist", name="created_at", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="todolist", name="updated_at", field=models.DateTimeField(),
        ),
    ]
