# Generated by Django 4.1.2 on 2022-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todolist_created_at_alter_todolist_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
