# Generated by Django 4.1.2 on 2022-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_auto_20221024_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
