# Generated by Django 4.1.2 on 2022-10-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_todolist_created_at_alter_todolist_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
